seed: 42

resume_path: ''
experiment_group: test
experiment_name: ${task.name}_${acq.name}_run_${seed}
save_path: results/${experiment_group}/${task.name}/${acq.name}_${seed}

defaults:
  - model: singletask
  - acqopt: medium
  - acq: lognei
  - task: branin
  - init: sobol
